
declare sub INIT_CHARACTER()
declare sub UPDATE_CHARACTER()

sub INIT_CHARACTER()
  CHARACTER.CELL_ID = 10
  CHARACTER.X = 0
  CHARACTER.Y = CAMERA.HEIGHT_HALF
end sub


sub UPDATE_CHARACTER()
  CHARACTER.Y = CHUNK( 5 ).CELL( CHARACTER.CELL_ID ).WALL_Y_BOTTOM( 0 ) + ( CHARACTER.X * CHUNK( 5 ).CELL( CHARACTER.CELL_ID ).WALL_SLOPE_BOTTOM ) - 17
end sub